### ISSUE TITLE
Problem import classpath*: oauth2 tag <client-registrations> bean duplicates 

### ISSUE THREAD

**Issue by mayaugusto7** [spring-projects/spring-security-samples#103]
When we using the ```<import resource="classpath*:..">``` happens the error bellow. 

> Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'org.springframework.security.oauth2.client.registration.ClientRegistrationRepository' available: expected single matching bean but found 4: org.springframework.security.oauth2.client.registration.InMemoryClientRegistrationRepository#0,org.spmatching bean but found 4: org.springframework.security.oauth2.client.registration.InMemoryClientRegistrationRepository#0,org.springframework.security.oauth2.client.registration.InMemoryClientRegistrationRepository#1,org.springframework.security.oauth2.client.registration.InMemoryClientRegistrationRepository#2,org.springframework.security.oauth2.client.registration.InMemoryClientRegistrationRepository#3

```
<import resource="classpath*:applicationContext-oauth2.xml"/> 
```

The content applicationContext-oauth2.xml

```
 <sec:http auto-config="true">
       <sec:intercept-url pattern="/**" access="authenticated"/>
       <sec:oauth2-login authorized-client-repository-ref="authorizedClientRepository"  />
 </sec:http>

    <sec:client-registrations>
       <sec:client-registration 
                                                   registration-id="google"
						 client-id="google-client-id"
						 client-secret="google-client-secret"
						 provider-id="google"/>
       <sec:provider   provider-id="google" />
    </sec:client-registrations>

    <bean name="authorizedClientService"class="org.springframework.security.oauth2.client.InMemoryOAuth2AuthorizedClientService" autowire="constructor"/>

    <bean id="authorizedClientRepository" class="org.springframework.security.oauth2.client.web.AuthenticatedPrincipalOAuth2AuthorizedClientRepository">
         <constructor-arg ref="authorizedClientService"/>
    </bean>
```
Could anyone help me with this problem?

**Comment by marcusdacoregio** [comment]
Hi @mayaugusto7, are you sure that you do not have any other XML file configuring `ClientRegistrationRepository` beans?

It looks like, from the error message, there are 4 beans of that type in your configuration.

**Comment by mayaugusto7** [comment]
Hi @marcusdacoregio thank you for your answer. We discovered our architecture is causing the problem.
