### ISSUE TITLE
SAML2 customize logout redirect URL

### ISSUE THREAD

**Issue by zeyugan** [spring-projects/spring-security-samples#104]
Hi there,

I'm trying to implement a saml2.0 single logout feature in my spring-boot app and can successfully log user out with:
`
			.saml2Logout(Customizer.withDefaults());
`
I want to redirect to another frontend URL after successful logout, but can't seem to find any sample for this.

I've read the documentation (https://docs.spring.io/spring-security/reference/servlet/saml2/logout.html) but it doesn't seem to cover this customization either.

Can I check if there's any quick configuration or sample that I can refer to for this?
Any help is appreciated!

**Comment by marcusdacoregio** [comment]
Hi @zeyugan, you can use the `logout` DSL to achieve this, like so:

```java
SimpleUrlLogoutSuccessHandler logoutSuccessHandler = new SimpleUrlLogoutSuccessHandler();
logoutSuccessHandler.setDefaultTargetUrl("https://mydomain.com/login");

http
	// ...
	.logout((logout) -> logout.logoutSuccessHandler(logoutSuccessHandler))
	.saml2Logout(withDefaults())
	// ...
```

When doing this, the `Saml2LogoutConfigurer` will pick up whatever `LogoutSuccessHandler` is configured in `LogoutConfigurer`, take a look at the [source code](https://github.com/spring-projects/spring-security/blob/177e11fbd723a0f87e44b8942f42fc40d7b45f60/config/src/main/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LogoutConfigurer.java#L215-L218) for `Saml2LogoutConfigurer`.

**Comment by zeyugan** [comment]
> Hi @zeyugan, you can use the `logout` DSL to achieve this, like so:
> 
> ```java
> SimpleUrlLogoutSuccessHandler logoutSuccessHandler = new SimpleUrlLogoutSuccessHandler();
> logoutSuccessHandler.setDefaultTargetUrl("https://mydomain.com/login");
> 
> http
> 	// ...
> 	.logout((logout) -> logout.logoutSuccessHandler(logoutSuccessHandler))
> 	.saml2Logout(withDefaults())
> 	// ...
> ```
> 
> When doing this, the `Saml2LogoutConfigurer` will pick up whatever `LogoutSuccessHandler` is configured in `LogoutConfigurer`, take a look at the [source code](https://github.com/spring-projects/spring-security/blob/177e11fbd723a0f87e44b8942f42fc40d7b45f60/config/src/main/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LogoutConfigurer.java#L215-L218) for `Saml2LogoutConfigurer`.

Hello @marcusdacoregio, thank you so much for the help!
