### ISSUE TITLE
Public and private keys for JWT decoder & encoder

### ISSUE THREAD

**Issue by EternalSadnes** [spring-projects/spring-security-samples#108]
I couldn't find information or a guide on how to generate those keys by myself. Could anyone please help?
Here is the link to folder with keys https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/jwt/login/src/main/resources

**Comment by marcusdacoregio** [comment]
Hi @EternalSadnes,

you can generate the public/private key pair with the following command:

`ssh-keygen -t rsa -b 4096 -m PEM -f jwtRS256.key`
