### ISSUE TITLE
Why the need to write logic to manually generate the JWT token?

### ISSUE THREAD

**Issue by hannah23280** [spring-projects/spring-security-samples#115]
Hi,
   Thanks for these samples project. It really helps a lot, especially me as a beginner in JTW. I am currently trying to implement JWT without involving oauth2, so your tutorial really helps.  But have query to consult you: 

In the token controller, i see that you have implement the generation of jwt token manually (see below).  Does the "spring-boot-starter-oauth2-resource-server" provides any built-in method to generate the token , rather than having us to write these manually?  
In my understanding I thought spring security (or spring-boot-starter-oauth2-resource-server) should provide a JWTTokenGeneration filter after the AuthenticationFilter, such that once authenticated successful (during login), the JWTTokenGeneration filter would automatically generate a jwt token ,similar to what u does below, except add it to the response header.instead of response body.  With that, developers are abstracted from having to write their own logic to generate the jwt token
```
public String token(Authentication authentication) {
		Instant now = Instant.now();
		long expiry = 36000L;
		// @formatter:off
		String scope = authentication.getAuthorities().stream()
				.map(GrantedAuthority::getAuthority)
				.collect(Collectors.joining(" "));
		JwtClaimsSet claims = JwtClaimsSet.builder()
				.issuer("self")
				.issuedAt(now)
				.expiresAt(now.plusSeconds(expiry))
				.subject(authentication.getName())
				.claim("scope", scope)
				.build();
		// @formatter:on
		return this.encoder.encode(JwtEncoderParameters.from(claims)).getTokenValue();
	}
```

**Comment by alimodares2003** [comment]
To generate JWT automatically, consider utilizing the `spring-security-oauth2-authorization-server`.

Find further information below:
https://github.com/spring-projects/spring-security-samples/blob/main/servlet/spring-boot/java/oauth2/authorization-server/README.adoc

**Comment by marcusdacoregio** [comment]
Hi @hannah23280.

> Does the "spring-boot-starter-oauth2-resource-server" provides any built-in method to generate the token , rather than having us to write these manually?

I don't think so. We advise against generating the token outside of the authorization server because doing that makes some things difficult, like refresh token, token invalidation, etc. The intention of this sample is to give you an idea how it would look like, and, from there, implement your own.
