### ISSUE TITLE
Authorities in scope of JWT

### ISSUE THREAD

**Issue by simasch** [spring-projects/spring-security-samples#118]
In the example jwt/login the authorities are added to the claim "scope".

.claim("scope", scope)

This looks find for the request with BasicAuth in method TokenContoroller.token() but in the HelloController.hello the authority becomes a prefix SCOPE:

![image](https://user-images.githubusercontent.com/593352/212949472-eb27dd38-5880-45b6-bf07-1ee1f354c482.png)

What would be the correct way to put authorities in the JWT token that it will contained correctly in the JwtAuthenticationToken?

**Comment by marcusdacoregio** [comment]
Hi @simasch,

The `oauth2ResourceServer` support adds the `SCOPE_` prefix to avoid collisions in authorities. To customize that, you can provide your own `JwtAuthenticationConverter` as documented [here](https://docs.spring.io/spring-security/reference/servlet/oauth2/resource-server/jwt.html#oauth2resourceserver-jwt-authorization-extraction) in the `Authorities Prefix Configuration`.

The configuration would look like this:

```java
@Bean
public JwtAuthenticationConverter jwtAuthenticationConverter() {
    JwtGrantedAuthoritiesConverter grantedAuthoritiesConverter = new JwtGrantedAuthoritiesConverter();
    grantedAuthoritiesConverter.setAuthorityPrefix(""); // Remove the prefix

    JwtAuthenticationConverter jwtAuthenticationConverter = new JwtAuthenticationConverter();
    jwtAuthenticationConverter.setJwtGrantedAuthoritiesConverter(grantedAuthoritiesConverter);
    return jwtAuthenticationConverter;
}
```

**Comment by simasch** [comment]
Thank you very much, again!
