### ISSUE TITLE
How to configure the public void configure(WebSecurity web) method in WebSecurityConfigurerAdapter in the new version?

### ISSUE THREAD

**Issue by lzcxfz** [spring-projects/spring-security-samples#119]
```java
   @Bean
    public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
        return http
                .authorizeRequests(req->req
                        .antMatchers("/user/login").permitAll()
                        .antMatchers("/hello2").hasAuthority("/hello2")
                        .anyRequest().authenticated())
                .sessionManagement(se->se.sessionCreationPolicy(SessionCreationPolicy.STATELESS))

                .csrf(csrf->csrf.disable())
                .cors(cors->cors.configurationSource(this.corsConfigurationSource())).build();

    }
```
The above code can only configure HttpSecurity. I want to configure WebSecurity now. How can I modify it?

**Comment by marcusdacoregio** [comment]
Hi @lzcxfz, you may want to read the [Migrate to 6.0 guide](https://docs.spring.io/spring-security/reference/5.8/migration/servlet/config.html#_publish_a_websecuritycustomizer_bean) that shows how to configure the filter chain without the `WebSecurityConfigurerAdapter`. There is also a [blog post](https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter) that summarizes the changes.

**Comment by lzcxfz** [comment]
@marcusdacoregio Oh, my God! Thank you so much.
