### ISSUE TITLE
SAML2 sample okta test credentials are not valid

### ISSUE THREAD

**Issue by taras-dzyk** [spring-projects/spring-security-samples#124]
Trying to run SAML2 login sample: https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/saml2/login

Cannot login to OKTA test IDP with credentials provided:
User: testuser@spring.security.saml
Password: 12345678

<img width="227" alt="image" src="https://user-images.githubusercontent.com/43788318/221931690-3464ea7a-d5c9-4c6c-bf36-eaddb88179f0.png">

**Comment by marcusdacoregio** [comment]
Hi @taras-dzyk, can you try to use `testuser2@spring.security.saml` and the same password?

For some reason the `testuser` user stopped working.

**Comment by taras-dzyk** [comment]
Hey @marcusdacoregio testuser2 works as expected. Thank you very much for help!

**Comment by marcusdacoregio** [comment]
Thanks for confirming, I'll leave this open for now to fix the READMEs
