### ISSUE TITLE
In the case of microservices， jwt

### ISSUE THREAD

**Issue by victory-wu** [spring-projects/spring-security-samples#130]
Microservice A  and  Microservice B and  Microservice C  。。。。。。：
Verify that jwt uses the same key？

Is there a security issue if the secret key is lost?

**Comment by marcusdacoregio** [comment]
Hi @victory-wu, I feel that this question is better suited for StackOverflow since it is not exactly related to the samples.

I'll close this but feel free to add the link to the StackOverflow question if you want.
