### ISSUE TITLE
DaoAuthenticationProvider

### ISSUE THREAD

**Issue by harshrathod50** [spring-projects/spring-security-samples#136]
Is it on purpose that there is no example here for `DaoAuthenticationProvider`?

**Comment by marcusdacoregio** [comment]
I don't think I follow your question @harshrathod50. The `DaoAuthenticationProvider` is used usually where it is needed an `UserDetailsService`.

Can you clarify what kind of sample do you expect to see?

**Comment by harshrathod50** [comment]
I want a sample which explicitly shows how to use `DaoAuthenticationProvider`.

**Comment by marcusdacoregio** [comment]
You are free to contribute if you come up with a common use-case. I will close this for the time being since the request is too vague.

**Comment by harshrathod50** [comment]
Very interesting, instead of asking me more questions and making things clear, you went one-step forward and closed this issue. Why not completely delete it? Problem solved! 😉
