### ISSUE TITLE
Multi factor authentication always redirect to /login even when using correct code for /second-factor

### ISSUE THREAD

**Issue by alishir** [spring-projects/spring-security-samples#148]
I just launched the multi-factor example, login with `user@example.com` and `password`, generate the TOTP code with `oathtool --totp  "80ed266dd80bcd32564f0f4aaa8d9b149a2b1eaa" ` command and enter the code, but I redirected to /login.

The problem exists on Chrome browser, with Firefox it works fine.

**Comment by sugarjig** [comment]
In case it helps anyone in the future, I was able to solve the error after the `/third-factor` page. I came across this issue: https://github.com/spring-projects/spring-security/issues/12635#issuecomment-1468046651, which led me to add
```java
.dispatcherTypeMatchers(DispatcherType.ERROR).permitAll()
```
inside `authorizeHttpRequests`.

**Comment by sugarjig** [comment]
This also appears to have fixed the issue with `favicon.ico`. I'm getting a 404 instead of a 302.

<img width="531" alt="image" src="https://github.com/spring-projects/spring-security-samples/assets/639693/fd600b19-cb84-4b4e-bde9-c4db442db0ea">

**Comment by sugarjig** [comment]
And it fixed the issue in Chrome!

**Comment by sugarjig** [comment]
I have created a [branch](https://github.com/spring-projects/spring-security-samples/compare/main...sugarjig:spring-security-samples:fix-mfa-sample) in my fork of the repo. TBH I don't know Spring Security well enough to know if this is an acceptable solution. Is this worthy of a PR?

**Comment by marcusdacoregio** [comment]
Thanks everyone, this has been fixed via https://github.com/spring-projects/spring-security-samples/commit/345bd64cf7e019d3b9ea3c799c6af70b38924c58 and merged into `6.1.x`, `6.2.x` and `main`.

**Comment by sugarjig** [comment]
@marcusdacoregio Thanks. It looks like your fix helped with the second factor, but now the third factor is redirecting to the error page.

<img width="653" alt="image" src="https://github.com/spring-projects/spring-security-samples/assets/639693/d5df71b6-ee73-43ee-a871-ea6239d8d72f">

**Comment by marcusdacoregio** [comment]
@sugarjig, sorry for the trouble. I'll try to take a look at it next week.

**Comment by marcusdacoregio** [comment]
@sugarjig how did you reproduce it? I couldn't have the same result on my side, when I provided incorrect information it redirects my to `/login` as expected.

**Comment by sugarjig** [comment]
@marcusdacoregio I just tried it again in Chrome. The first time failed, but then a second and third try succeeded. Each try was in a fresh incognito window. Not quite sure what's going on, but it's likely on my end!
