### ISSUE TITLE
Unable to Retrieve Refresh Token

### ISSUE THREAD

**Issue by firasrg** [spring-projects/spring-security-samples#175]
I am currently working with the [JWT Login Sample](https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/jwt/login#jwt-login-sample) that demonstrates how to issue JWT tokens for a REST API. The sample works well for obtaining an access token, but I am facing difficulties in retrieving a _refresh token_. 

I even followed the [oauth2/auhtorization-server sample](https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/oauth2/authorization-server), but unfortenately it can't give any refresh token (check screenshot). So im confused here and tired please help me. 

My purpose is simple: I want a simple authorization service or spring boot app without the need to hand write the logic for access and refresh tokens. I'd appreciate to know about further interesting features such as persisting data in db or account recovery. 

thanks!

![image](https://github.com/spring-projects/spring-security-samples/assets/37019463/7c0444fa-6ed7-4c1c-bfaf-fa755988e6bc)

**Comment by marcusdacoregio** [comment]
Hi, @firasrg.

To be able to generate refresh token using the Spring Authorization Server your client must have the refresh token authorization grant type https://github.com/spring-projects/spring-security-samples/blob/25fadf08ab794e54029fbbb2ce2f7dd6c0d55493/servlet/spring-boot/java/oauth2/authorization-server/src/main/java/example/OAuth2AuthorizationServerSecurityConfiguration.java#L105.

If you need further assistance please consider asking a question on StackOverflow, we prefer to keep the issue tracker focused on bugs or enhancements.

**Comment by firasrg** [comment]
Hi @marcusdacoregio! 

The client is NOT a Spring Boot app, it's actually a separate web app. As i mentioned, i've tried with the authorization server, but when i send request with grant_type = refresh_token, i get an error it said wrong grant_type ! what i wan't is a sample that work for REST API.

**Comment by marcusdacoregio** [comment]
The `refresh_token` grant type does not provide you a refresh token, it is used to exchange a previously generated refresh token to a access token. You should probably be using `authorization_code` grant type.

**Comment by firasrg** [comment]
I've tried with that too (authorization_code), but it want's a redirection url, which is not my purpose ! I want a very simple thing: when i call `/token` , i want 2 tokens back access and refresh which is not working actually 😅
