### ISSUE TITLE
[invalid_scope] OpenID Connect 1.0 authentication requests are restricted.

### ISSUE THREAD

**Issue by gongzelong0718** [spring-projects/spring-security-samples#217]
https://github.com/spring-projects/spring-security-samples/tree/6.2.x/servlet/spring-boot/java/oauth2/login#spring-login

> Boot up the application
> Launch the Spring Boot 2.0 sample and go to http://127.0.0.1:8080/. You are then redirected to the default auto-generated login page, which displays a link for Spring.
> 
> Click on the Spring link, and you are then redirected to the Spring Authorization Server for authentication.
> 
> After authenticating with your credentials (user and password by default), the next page presented to you is the Consent screen. The Consent screen asks you to either allow or deny access to the OAuth Client. Select "profile" and click Submit Consent to authorize the OAuth Client to access your basic profile information.

But from my test, after authenticating with your credentials (user and password by default), it shows in the page http://127.0.0.1:8080/login?error

[invalid_scope] OpenID Connect 1.0 authentication requests are restricted.

I checked that the scope has profile. 

Is it an issue?

**Comment by lorenzBern** [comment]
I have the same problem
