### ISSUE TITLE
Update Saml 2 samples to use a mock IdP

### ISSUE THREAD

**Issue by jzheaux** [spring-projects/spring-security-samples#324]
Currently, the samples point to an Okta endpoint, which is out of our control. Recently they [had an outage](https://status.okta.com/#incident/a9C4z000001BZbnEAG) that caused our tests to fail for a period of time. The tests would be more resilient if they used a mock IdP.

**Comment by marcusdacoregio** [comment]
Related to https://github.com/spring-projects/spring-security-samples/issues/127

**Comment by jzheaux** [comment]
Closing in favor of #127
