### ISSUE TITLE
OAuth2AuthorizationServerSecurityConfiguration

### ISSUE THREAD

**Issue by lorenzBern** [spring-projects/spring-security-samples#339]
The OAuth2AuthorizationServerSecurityConfiguration.java is removed in main Branch. Could you provide an example for spring-security-oauth2-authorization-server Version 1.4?

https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/oauth2/authorization-server/src/main/java/example

**Comment by sjohnr** [comment]
Thanks for the question @lorenzBern! Please see the [Defining Required Components](https://docs.spring.io/spring-authorization-server/reference/getting-started.html#defining-required-components) section of the [Spring Authorization Server reference](https://docs.spring.io/spring-authorization-server/reference/index.html) for an example. The goal of this sample is to show a minimal authz server setup. We might also want to show a less minimal example, but such examples are already in the [Spring Authorization Server samples](https://github.com/spring-projects/spring-authorization-server/tree/main/samples) themselves. I'll close this as answered.
