### ISSUE TITLE
Add index page of samples

### ISSUE THREAD

**Issue by sjohnr** [spring-projects/spring-security-samples#41]
Such as:
* Add a table of contents to the readme
* Add a wiki page
* Create a simple documentation microsite (e.g. [Antora](https://antora.org/)) with organized list
* Create a simple [GitHub Pages](https://pages.github.com/) site with organized list

**Comment by marcusdacoregio** [comment]
Fixed via https://github.com/spring-projects/spring-security-samples/commit/bf1ca80a0a78c344843437b960a3bb19f3639e78
