### ISSUE TITLE
why i can not find JwtEncoder in spring-boot-starter-oauth2-resource-server:2.5.3?

### ISSUE THREAD

**Issue by youlanqiang** [spring-projects/spring-security-samples#47]
<img width="436" alt="截屏2021-10-29 下午5 54 50" src="https://user-images.githubusercontent.com/32521712/139415237-70a4c56d-8f67-479d-97d6-779113ece680.png">

<img width="989" alt="截屏2021-10-29 下午5 54 36" src="https://user-images.githubusercontent.com/32521712/139415269-020d9c7f-f66d-4a0f-aebb-27760e60ddf8.png">

<img width="790" alt="截屏2021-10-29 下午5 56 07" src="https://user-images.githubusercontent.com/32521712/139415438-86ecc407-7475-4fbd-a582-d25482fc352f.png">

**Comment by sjohnr** [comment]
@youlanqiang, the `JwtEncoder` is in the upcoming 5.6 release. If you'd like to work with it in your own project, you can add it to your `build.gradle`:

```gradle
repositories {
    maven { url "https://repo.spring.io/milestone" }
}
```

and `gradle.properties`:

```properties
spring-security.version=5.6.0-RC1
```
