### ISSUE TITLE
Multi-factor authentication Sample Bug: Refreshing the page when in second-factor page redirects to login page

### ISSUE THREAD

**Issue by imtiazShakil** [spring-projects/spring-security-samples#63]
### How to reproduce:    

start the mfa spring boot application
```bash
./gradlew -b ./servlet/spring-boot/java/authentication/username-password/mfa/build.gradle bootRun
```
giving credentials in first page (_user@example.com, password_) redirects to second page but when in second page: 
- If I refresh, I get `AnonymousAuthenticationToken` inside `SecurityConfig#mfaAuthorizationManager`
- if I submit totp code I still get `AnonymousAuthenticationToken` inside `SecurityConfig#mfaAuthorizationManager`

Both of the above event leads me back to login page.

**Comment by c-a-m** [comment]
I'm seeing the same thing.  I've tried the main branch with java 17 and [the 5.5.x branch](https://github.com/spring-projects/spring-security-samples/tree/5.5.x) with java 8 and I can't get past the second factor.

Debugging through it the method `MfaController.processSecondFactor` is never invoked.

**Comment by sjohnr** [comment]
@imtiazShakil @c-a-m - Thanks for reaching out!

When I try the sample, and refresh on the 2nd factor page, I eventually get a 404 error. There does appear to be an issue in the two locations where the `SecurityContext` is updated. The pattern for updating should be:

```java
SecurityContext securityContext = SecurityContextHolder.createEmptyContext();
securityContext.setAuthentication(authentication);
SecurityContextHolder.setContext(securityContext);
```

We could look into applying this update to the various samples, which would seem to fix the issue I encountered. However, I'm unable to reproduce any of the reports you mentioned.

> * If I refresh, I get AnonymousAuthenticationToken inside SecurityConfig#mfaAuthorizationManager
> * if I submit totp code I still get AnonymousAuthenticationToken inside SecurityConfig#mfaAuthorizationManager

> I can't get past the second factor.

I'm running the sample on the `main` branch with JDK 17. Can you provide more context or debugging information? Trace logging can be enabled by creating `src/main/resources/application.yml` with the following:

```yaml
logging:
  level:
    org.springframework.security: trace
```

Or run with -Dlogging.level.org.springframework.security=trace`.

**Comment by c-a-m** [comment]
@sjohnr with the trace on we figured out that requests to the favicon.ico is causing my browser(Chrome) to go back to the username/password login page.  Making it public seemed to resolve it for me so I put a PR out with that minor change.

**Comment by sjohnr** [comment]
@c-a-m Interesting! I suppose I'm using a different browser and may not experience that issue the same way or at all. We can merge that and give it a try to see if it improves the situation for others.

**Comment by fengshao3** [comment]
@sjohnr  I'm seeing the same thing， I've tried the main branch with java 17  ，log is 

`  : Securing POST /second-factor
2023-06-29T15:07:52.760+08:00 TRACE 12744 --- [nio-8080-exec-2] o.s.security.web.FilterChainProxy        : Invoking DisableEncodeUrlFilter (1/14)
2023-06-29T15:07:52.760+08:00 TRACE 12744 --- [nio-8080-exec-2] o.s.security.web.FilterChainProxy        : Invoking WebAsyncManagerIntegrationFilter (2/14)
2023-06-29T15:07:52.760+08:00 TRACE 12744 --- [nio-8080-exec-2] o.s.security.web.FilterChainProxy        : Invoking SecurityContextPersistenceFilter (3/14)
2023-06-29T15:07:52.760+08:00 TRACE 12744 --- [nio-8080-exec-2] w.c.HttpSessionSecurityContextRepository : Did not find SecurityContext in HttpSession EBB9ACFC6FF83E6DA9FE285F7468F9C9 using the SPRING_SECURITY_CONTEXT session attribute
2023-06-29T15:07:52.760+08:00 TRACE 12744 --- [nio-8080-exec-2] w.c.HttpSessionSecurityContextRepository : Created SecurityContextImpl [Null authentication]
2023-06-29T15:07:52.760+08:00 TRACE 12744 --- [nio-8080-exec-2] .s.s.w.c.SupplierDeferredSecurityContext : Created SecurityContextImpl [Null authentication]`
我发现了同样的问题，用的是main分支，jdk17 ，
![微信截图_20230629154301](https://github.com/spring-projects/spring-security-samples/assets/41541446/d94b9b5e-02fa-468f-b78e-83292b9f37d9)
![微信截图_20230629154414](https://github.com/spring-projects/spring-security-samples/assets/41541446/b43b7871-1ccb-4d63-9a31-3e52990d0c8a)
英语不太好，见谅。
