### ISSUE TITLE
SAML 2.0 Login & Logout Sample failed to run

### ISSUE THREAD

**Issue by zhanedw-statcan** [spring-projects/spring-security-samples#82]
On the branch 5.7.x, in the saml2 sample - "spring-security-samples-5.7.x/servlet/xml/java/saml2/login-logout", try to run 

 ./gradlew :spring-security-samples-boot-saml2login:bootRun

got the error:

FAILURE: Build failed with an exception.

* What went wrong:
Project 'spring-security-samples-boot-saml2login' not found in root project 'spring-security-samples-5.7.x'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plug

See https://docs.gradle.org/7.3.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5s

**Comment by zhanedw-statcan** [comment]
It looks like that we need to use '**appRun**' task,

./gradlew :spring-security-samples-boot-saml2login:appRun

**Comment by marcusdacoregio** [comment]
Hi @zhanedw-statcan, thanks for the report.

The command should be `./gradlew :servlet:spring-boot:java:saml2:login:bootRun`

**Comment by marcusdacoregio** [comment]
This is now fixed via https://github.com/spring-projects/spring-security-samples/commit/1fc20d346e4c5d486b3283087df3c88d21e77313.

Thank you!
