### ISSUE TITLE
okta saml 2 configuration for servlet/xml/java/saml2/login-logout

### ISSUE THREAD

**Issue by zhanedw-statcan** [spring-projects/spring-security-samples#84]
Is it possible to share the okta saml configuration for this sample project, especially for "servlet/xml/java/saml2/login-logout"?

As I am trying the "servlet/xml/java/saml2/login-logout" code with my own okta saml configuration, the login works fine, but the logout always gives me the error:
![image](https://user-images.githubusercontent.com/109087297/181115712-ae77b007-5835-44d7-8925-24a0bf2ff45a.png)

**Comment by marcusdacoregio** [comment]
Hi @zhanedw-statcan.

Can you add `logging.level.org.springframework.security=TRACE` to your `application.properties` and see the console output after the error is presented?

**Comment by zhanedw-statcan** [comment]
I saw the error: **SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".**, see the log below.

Also, I did not see the file `application.properties`, only see the file `logback.xml`

Here is the log from console:


> $ ./gradlew appRun
> Jul 27, 2022 10:30:09 AM org.apache.coyote.AbstractProtocol init
> INFO: Initializing ProtocolHandler ["http-nio-8080"]
> Jul 27, 2022 10:30:09 AM org.apache.catalina.core.StandardService startInternal
> INFO: Starting service [Tomcat]
> Jul 27, 2022 10:30:09 AM org.apache.catalina.core.StandardEngine startInternal
> INFO: Starting Servlet engine: [Apache Tomcat/9.0.50]
> Jul 27, 2022 10:30:09 AM org.apache.coyote.AbstractProtocol start
> INFO: Starting ProtocolHandler ["http-nio-8080"]
> Jul 27, 2022 10:30:17 AM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
> INFO: No global web.xml found
> Jul 27, 2022 10:30:22 AM org.apache.jasper.servlet.TldScanner scanJars
> INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
> Jul 27, 2022 10:30:22 AM org.apache.catalina.core.ApplicationContext log
> INFO: No Spring WebApplicationInitializer types detected on classpath
> Jul 27, 2022 10:30:22 AM org.apache.catalina.core.ApplicationContext log
> INFO: Initializing Spring root WebApplicationContext
> **SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".**
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> 10:30:27 INFO  Tomcat 9.0.50 started and listening on port 8080
> 10:30:27 INFO   runs at:
> 10:30:27 INFO    http://localhost:8080
> 
> > Task :appRun
> Press any key to stop the server.
> <===========--> 87% EXECUTING [1m 2s]
> > :appRun
>

**Comment by marcusdacoregio** [comment]
For logout, you have to upload the **Signature Certificate** in Okta. In the sample, we have uploaded the `rp-certificate.cert`.

**Comment by marcusdacoregio** [comment]
Don't forget to add `logging.level.org.springframework.security=TRACE` to your `application.properties` so you can see what is the problem.

**Comment by zhanedw-statcan** [comment]
I ended up with the spring-boot log from "servlet/spring-boot/java/saml2/login-single-tenant", and saw the problem in my okta configuration. After I fixed the okta configuration issue, it works fine now. Thank you for your suggestion.
