### ISSUE TITLE
Missing Security Configuration File on Username-Password sample

### ISSUE THREAD

**Issue by lshannon** [spring-projects/spring-security-samples#89]
Trying to learn the new way of configuring Security using SecurityFilterChain for a Form Login. Can this sample be updated to include a best practice SecurityFilterChain configuration?

https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/authentication/username-password/user-details-service/custom-user/src/main/java/example

**Comment by marcusdacoregio** [comment]
Hi @lshannon.

The sample that you linked does not explicitly configure the `SecurityFilterChain`. It uses the default configuration from Spring Boot. The only bean overridden is the `UserDetailsService`, [here](https://github.com/spring-projects/spring-security-samples/blob/6bed57d79bd59f7eba0541e806fb42ed63f165e6/servlet/spring-boot/java/authentication/username-password/user-details-service/custom-user/src/main/java/example/UserDetailsServiceApplication.java#L38-L53).

**Comment by lshannon** [comment]
Perfect! Thanks!
