### ISSUE TITLE
Test failed on a Resource server when using Spring WebMvc RouterFunction

### ISSUE THREAD

**Issue by hantsy** [spring-projects/spring-security-samples#9]
I created a **Resource server** example project using Spring WebMvc RouterFunction and Auth0 IDP.

https://github.com/hantsy/spring-webmvc-auth0-sample

When adding tests, I followed the [Spring Security Samples](https://github.com/spring-projects/spring-security-samples/tree/master/servlet/spring-boot/java/oauth2/resource-server/hello-security/src/main/resources).

I tried to use `@MockMvc` to test the functionality but failed. The `@MockMvc` can not recognize `RouterFunction` bean and the new Spring Security Servlet `SecurityFilterChain`.

* https://github.com/hantsy/spring-webmvc-auth0-sample/blob/master/src/main/java/com/example/demo/config/WebConfig.java#L17
* https://github.com/hantsy/spring-webmvc-auth0-sample/blob/master/src/main/java/com/example/demo/config/SecurityConfig.java#L31

Then I created a `MockMvc` from `WebApplicationContext`, check https://github.com/hantsy/spring-webmvc-auth0-sample/blob/master/src/test/java/com/example/demo/ApplicationTests.java, but failed due to an exception.

```bash 
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException: Cannot invoke "org.springframework.test.web.servlet.DefaultMvcResult.setHandler(Object)" because "mvcResult" is null

    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
```

Also posted on stackoverflow, https://stackoverflow.com/questions/67171628/resource-server-test-failes-with-auth0-issuer-uri

**Comment by rwinch** [comment]
Thanks for getting in touch, but this does not appear to be a problem with the code in this repository as it is working. I think this question is better suited for StackOverflow which I and the rest of the security team monitors

**Comment by jzheaux** [comment]
Hi, @hantsy, thanks for the report. I've posted a response to your StackOverflow question.
