### ISSUE TITLE
How to configure oauth2 xml

### ISSUE THREAD

**Issue by mayaugusto7** [spring-projects/spring-security-samples#98]
Hello folks!

I'm trying to configure the oauth2 on XML. But do not understand how to create a clientRegistrationRepository bean.  

In the java class, the bean return is InMemoryClientRegistrationRepository, how to do this in XML?

This spring documentation [https://docs.spring.io/spring-security/reference/servlet/oauth2/login/core.html#oauth2login-javaconfig-wo-boot](oauth2)

**Comment by marcusdacoregio** [comment]
Hey, sorry for the delay is responding. Were you able to create the bean?

**Comment by mayaugusto7** [comment]
@marcusdacoregio  The client-registrations and client-registration tags were not being created correctly. I achieved to discover the problem.

Thanks!
